# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self

stages:
- stage: DeployToDefault
  displayName: Deploy to Default
  dependsOn: Build
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/'))
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool:
      name: work-machine
    environment: 'BikeSharingSampleApp-Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Production deployment!
            displayName: 'Production deployment'



