apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image:  atulmakshelm.azurecr.io/notification:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: expressapp
