apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image:  atulmakshelm.azurecr.io/payment:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: expressapp
