apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: email
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image:  atulmakshelm.azurecr.io/email:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: expressapp
