apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: cncfdemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cncfdemo 
    spec:
      containers:
        - name: cncfdemo 
          image: builddemo.azurecr.io/cncfdemo 
          ports:
          - containerPort: 3000